# Generated by Django 3.2.25 on 2024-09-11 21:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240905_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavHomeRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cooked', models.DateField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='core.home')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe')),
            ],
        ),
    ]
