# Generated by Django 3.2.25 on 2024-09-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_favhomerecipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favhomerecipe',
            name='last_cooked',
            field=models.DateField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='favhomerecipe',
            unique_together={('home', 'recipe')},
        ),
    ]
