# Generated by Django 3.2.25 on 2024-09-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_favhomerecipe_last_cooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='amount_unit',
            field=models.CharField(default='g', max_length=100),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('mandatory', models.BooleanField(default=False)),
                ('amount_unit', models.CharField(max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe')),
            ],
            options={
                'unique_together': {('ingredient', 'recipe')},
            },
        ),
    ]
